// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;
  

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAhk-_N-zsnnIoVUZxdpWfcysmDD4qTUlE',
    appId: '1:816395259813:web:6315ec25bb34083646a24c',
    messagingSenderId: '816395259813',
    projectId: 'agribot-project-b1947',
    authDomain: 'agribot-project-b1947.firebaseapp.com',
    storageBucket: 'agribot-project-b1947.firebasestorage.app',
    measurementId: 'G-S36YHM295T',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAOoKnp3_hFEsIQbzQR2hsa2ZS1rX-qXJg',
    appId: '1:816395259813:android:98da4c6e30b30dd746a24c',
    messagingSenderId: '816395259813',
    projectId: 'agribot-project-b1947',
    storageBucket: 'agribot-project-b1947.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDtwDcZl_HdP47XhZmKUWWCT0_NLPtmf8g',
    appId: '1:816395259813:ios:b1013fcfde87755546a24c',
    messagingSenderId: '816395259813',
    projectId: 'agribot-project-b1947',
    storageBucket: 'agribot-project-b1947.firebasestorage.app',
    iosBundleId: 'com.example.agribot',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDtwDcZl_HdP47XhZmKUWWCT0_NLPtmf8g',
    appId: '1:816395259813:ios:b1013fcfde87755546a24c',
    messagingSenderId: '816395259813',
    projectId: 'agribot-project-b1947',
    storageBucket: 'agribot-project-b1947.firebasestorage.app',
    iosBundleId: 'com.example.agribot',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAhk-_N-zsnnIoVUZxdpWfcysmDD4qTUlE',
    appId: '1:816395259813:web:2b65cd395a75414f46a24c',
    messagingSenderId: '816395259813',
    projectId: 'agribot-project-b1947',
    authDomain: 'agribot-project-b1947.firebaseapp.com',
    storageBucket: 'agribot-project-b1947.firebasestorage.app',
    measurementId: 'G-V4S82GCVZT',
  );
}
