// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;
  

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAEY0mwBv8X0QEPtlRK9NGLgelCqrfgUik',
    appId: '1:414685797737:web:df9af59e66fc0236f2f1f8',
    messagingSenderId: '414685797737',
    projectId: 'agribot-production',
    authDomain: 'agribot-production.firebaseapp.com',
    storageBucket: 'agribot-production.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBKTCeKFg_qJFiTi08X-Vwe3aZms6Etzns',
    appId: '1:414685797737:android:d25f65a7dc634ddaf2f1f8',
    messagingSenderId: '414685797737',
    projectId: 'agribot-production',
    storageBucket: 'agribot-production.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDtwDcZl_HdP47XhZmKUWWCT0_NLPtmf8g',
    appId: '1:816395259813:ios:b1013fcfde87755546a24c',
    messagingSenderId: '816395259813',
    projectId: 'agribot-project-b1947',
    storageBucket: 'agribot-project-b1947.firebasestorage.app',
    iosBundleId: 'com.example.agribot',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDtwDcZl_HdP47XhZmKUWWCT0_NLPtmf8g',
    appId: '1:816395259813:ios:b1013fcfde87755546a24c',
    messagingSenderId: '816395259813',
    projectId: 'agribot-project-b1947',
    storageBucket: 'agribot-project-b1947.firebasestorage.app',
    iosBundleId: 'com.example.agribot',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAEY0mwBv8X0QEPtlRK9NGLgelCqrfgUik',
    appId: '1:414685797737:web:4bf79c2c98e019b6f2f1f8',
    messagingSenderId: '414685797737',
    projectId: 'agribot-production',
    authDomain: 'agribot-production.firebaseapp.com',
    storageBucket: 'agribot-production.firebasestorage.app',
  );

}